### ISSUE TITLE
SAXException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

### ISSUE THREAD

**Issue by nekrasovweb** [chumovitskiy/KotlinTest#1]
C:\Yuriy\3\fias_xml\parseXml>java -cp "kotlin-stdlib.jar" -jar parseXml.jar --source C:\Yuriy\3\fias_xml\HOUSE.XML -t out.xml -s 2024M
SAXException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
C:\Yuriy\3\fias_xml\parseXml>java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by chumovitskiy** [comment]
I think it is incorrect header or incorrect encoding. Please will check theirs.

**Comment by nekrasovweb** [comment]
Incorrect encoding. It is possible to remove the BOM from a file with the tail command:
tail --bytes=+4 withBOM.txt > withoutBOM.txt

**Comment by chumovitskiy** [comment]
I added support UTF with BOM. There work correct now.
